package br.svcdev.common;

public enum CommandType {

   CMD_AUTH,
   CMD_AUTH_ERROR,
   CMD_BROADCAST_MESSAGE,
   CMD_END,
   CMD_ERROR,
   CMD_MESSAGE,
   CMD_PRIVATE_MESSAGE,
   CMD_REG,
   CMD_REG_REQUEST,
   CMD_UPDATE_NICKNAME,
   CMD_UPDATE_USERS_LIST
}
